# fpgago/Makefile — build orchestrator for the Commodore cores
#
#   make start                          desktop companion app (first run)
#   make run   ARCH=c64                 desktop simulation (Verilator + SDL2)
#   make build ARCH=c64 TARGET=fpga     synthesize a bitstream (yosys/nextpnr)
#   make clean                          remove build artifacts
#
# ARCH is one of: c64, c16, plus4.
#
# The KERNAL/BASIC/chargen ROMs are copyrighted and are NOT in this
# repository.  `make download-rom ARCH=<m>` fetches them from the VICE
# project after an explicit consent prompt; the bitstream bakes them in at
# synthesis, which is why that step comes first.

# Load tool paths from .config.mk (generated by ./setup.sh)
-include .config.mk

ifeq ($(OS),Windows_NT)
  EXEEXT = .exe
else
  EXEEXT =
endif

# Prevent TARGET from leaking into sub-Makefiles (they use TARGET for the
# binary name).
MAKEOVERRIDES := $(filter-out TARGET=%,$(MAKEOVERRIDES))

ARCHS   = c64 c16 plus4
retrodir = retro-arch/$(1)

.PHONY: help all check-deps start desktop desktop-venv clean \
        download-rom roms-container download-cpu download-game run-game \
        list-games run-floppy run-prg run build \
        check-easyflash check-efpush check-shot check-cpu check-drive \
        run-crt bitstreams

# ── Default target: show help ──────────────────────────────────────────────
help:
	@printf "\n"
	@printf "\033[1;32m  FPGAgo — Commodore 64 / 16 / Plus4 on an ECP5\033[0m\n"
	@printf "\n"
	@printf "\033[32m  Desktop app:\033[0m\n"
	@printf "    make start                                     First run: app + Install tab\n"
	@printf "    make desktop                                   Library, board remote, screen grab\n"
	@printf "\n"
	@printf "\033[32m  Machines (ARCH=c64 | c16 | plus4):\033[0m\n"
	@printf "    make download-rom  ARCH=<m>                    Download the firmware ROMs\n"
	@printf "    make download-cpu  ARCH=c64                    Download the c64 chip cores\n"
	@printf "    make run           ARCH=<m>                    Desktop simulation\n"
	@printf "    make build         ARCH=<m> TARGET=fpga        Synthesize a bitstream\n"
	@printf "    make roms-container ARCH=<m>                   Build <m>.roms for a ROM-free bit\n"
	@printf "\n"
	@printf "\033[32m  Games:\033[0m\n"
	@printf "    make list-games    ARCH=<m>                    What the catalog knows about\n"
	@printf "    make download-game ARCH=<m> GAME=<name>        Prepare a game you supplied\n"
	@printf "    make run-game      ARCH=<m> GAME=<name>        Build + run it\n"
	@printf "    make run-floppy    ARCH=<m> D64=<disk.d64> [PROGRAM=<name>] [FAST=1]\n"
	@printf "                                                   Run from the emulated 1541\n"
	@printf "    make run-floppy    ARCH=<m> PRG=<game.prg>     ...wrapping a PRG into a disk\n"
	@printf "    make run-prg       ARCH=<m> PRG=<game.prg> [TARGET=fpga]\n"
	@printf "                                                   Bake a PRG in and autostart it\n"
	@printf "    make run-crt       ARCH=c64 CRT=<cart.crt>     Run an EasyFlash cartridge\n"
	@printf "\n"
	@printf "\033[32m  Checks:\033[0m\n"
	@printf "    make check-cpu                                 6502 opcode conformance\n"
	@printf "    make check-easyflash ARCH=c64                  EasyFlash banking + flash emulation\n"
	@printf "    make check-efpush    ARCH=c64                  Cart image push over the link\n"
	@printf "    make check-shot      ARCH=c64                  Screen grab over the FPGA video path\n"
	@printf "    make check-drive                               The fabric 1541 vs the reference DOS\n"
	@printf "\n"
	@printf "\033[32m  Setup:\033[0m\n"
	@printf "    make check-deps                                Check installed tools\n"
	@printf "    make bitstreams                                Rebuild the committed ROM-free bits\n"
	@printf "\n"
	@printf "  New here? Run \033[1mmake start\033[0m — it opens the desktop app; the Install tab\n"
	@printf "  sets up the toolchain, the Commodore ROMs (consent required) and the\n"
	@printf "  bitstreams.\n"
	@printf "\n"

# ── Guards ─────────────────────────────────────────────────────────────────
# Every machine target needs a valid ARCH; say so once, in one place.
define need_arch
	@test -n "$(ARCH)" || { echo "Usage: make $@ ARCH=<arch>"; echo "Available: $(ARCHS)"; exit 1; }
	@test -d $(call retrodir,$(ARCH))/sim-desktop || { echo "Error: unknown ARCH=$(ARCH) (available: $(ARCHS))"; exit 1; }
endef

check-deps:
	@bash setup.sh check

all: $(ARCHS:%=build-%)

build-%:
	@$(MAKE) build ARCH=$*

# ── ROMs ───────────────────────────────────────────────────────────────────
download-rom:
	$(need_arch)
	@$(MAKE) -C $(call retrodir,$(ARCH))/sim-desktop download-$(ARCH)-rom

# Build the .roms container a ROMLESS bitstream eats (the board firmware
# pushes it from the flash file system after configuration).
roms-container:
	$(need_arch)
	@$(MAKE) -C $(call retrodir,$(ARCH))/sim-desktop roms-container \
	    $(if $(KICK),KICK=$(abspath $(KICK)),) $(if $(TRIM),TRIM=1,)

# Third-party chip cores (VIC-II, SID, CIA) — c64 only.
download-cpu:
	$(need_arch)
	@$(MAKE) -C $(call retrodir,$(ARCH))/sim-desktop download-cpu

# ── Games ──────────────────────────────────────────────────────────────────
list-games:
	$(need_arch)
	@$(MAKE) -C $(call retrodir,$(ARCH))/sim-desktop list-$(ARCH)-games

download-game:
	$(need_arch)
	@test -n "$(GAME)" || { echo "Usage: make download-game ARCH=<arch> GAME=<name>"; exit 1; }
	@$(MAKE) -C $(call retrodir,$(ARCH))/sim-desktop download-$(ARCH)-game GAME=$(GAME)

run-game:
	$(need_arch)
	@test -n "$(GAME)" || { echo "Usage: make run-game ARCH=<arch> GAME=<name>"; exit 1; }
	@$(MAKE) -C $(call retrodir,$(ARCH))/sim-desktop run-$(ARCH)-game GAME=$(GAME)

# Run from the EMULATED 1541 floppy.  Mounts a .d64; with PROGRAM= it also
# auto-types LOAD"NAME",8 + RUN, otherwise you type it yourself.  PRG=<game.prg>
# wraps the PRG into a fresh .d64 first (prg2d64.py) and auto-loads it.
# FAST=1 turns on the fast loader (direct RAM injection, bypassing the drive).
run-floppy:
	$(need_arch)
	@test -n "$(D64)" -o -n "$(PRG)" || { echo "Usage: make run-floppy ARCH=<arch> D64=<disk.d64>|PRG=<game.prg> [PROGRAM=<name>] [FAST=1]"; exit 1; }
	@D64PATH="$(abspath $(D64))"; PROGRAM="$(PROGRAM)"; \
	if [ -n "$(PRG)" ]; then \
	    test -f "$(PRG)" || { echo "PRG not found: $(PRG)"; exit 1; }; \
	    mkdir -p $(call retrodir,$(ARCH))/roms/games; \
	    D64PATH="$(abspath $(call retrodir,$(ARCH)))/roms/games/$$(basename "$(PRG)" .prg).d64"; \
	    echo "Wrapping $(PRG) into $$D64PATH..."; \
	    python3 retro-arch/common/prg2d64.py "$$D64PATH" "$(PRG)" || exit 1; \
	    test -n "$$PROGRAM" || PROGRAM="*"; \
	fi; \
	$(MAKE) -C $(call retrodir,$(ARCH))/sim-desktop run-$(ARCH)-floppy \
	    D64="$$D64PATH" PROGRAM="$$PROGRAM" FAST=$(FAST)

# Bake a local .prg into the machine's RAM init image and autostart it via the
# hardware boot_typer (works on the board with no host attached).
# TARGET=fpga builds a bitstream instead of running the simulation.
run-prg:
	$(need_arch)
	@test -n "$(PRG)" || { echo "Usage: make run-prg ARCH=<arch> PRG=<game.prg> [TARGET=fpga]"; exit 1; }
	@$(MAKE) -C $(call retrodir,$(ARCH))/sim-desktop run-$(ARCH)-prg \
	    PRG=$(abspath $(PRG)) TARGET=$(TARGET) HW=$(HW)

# ── EasyFlash cartridge (c64 — retro-arch/c64/README.md) ───────────────────
check-easyflash check-efpush:
	@$(MAKE) -C retro-arch/c64/sim-desktop $@

run-crt:
	@test -n "$(CRT)" || { echo "Usage: make run-crt ARCH=c64 CRT=<file.crt>"; exit 1; }
	@$(MAKE) -C retro-arch/c64/sim-desktop run-c64-crt CRT=$(abspath $(CRT))

# ── Regression checks ──────────────────────────────────────────────────────
# check-shot runs the SHOT_ARM/STATUS/READ sweep against the FPGA-mode video
# path — the branch of soc.v the bitstream uses, not the simulation one.
check-shot:
	@$(MAKE) -C $(call retrodir,$(or $(ARCH),c64))/sim-desktop check-shot

# 6502 opcode conformance (documented + undocumented).  The Arlet core is
# shared by all three machines, so run this after touching cpu_6502.v.
check-cpu:
	@$(MAKE) -C retro-arch/common/cpu/6502 check

# The fabric 1541 (retro-arch/common/drive1541) against the reference DOS.
check-drive:
	@$(MAKE) -C retro-arch/common/drive1541 check

# ── Build ──────────────────────────────────────────────────────────────────
# TARGET=fpga synthesizes a bitstream through the machine's run.sh; anything
# else builds the Verilator desktop simulation.
build:
	$(need_arch)
	@if [ "$(TARGET)" = "fpga" ]; then \
	    echo "Synthesizing $(ARCH) for FPGA..."; \
	    if [ ! -f "$(call retrodir,$(ARCH))/roms/bios_font_lo.hex" ]; then \
	        echo "Generating BIOS font (bios_font.py)..."; \
	        python3 retro-arch/common/bios_font.py; \
	    fi; \
	    cd $(call retrodir,$(ARCH)) && \
	    PATH="$(CURDIR)/oss-cad-suite/bin:$$PATH" \
	    $(if $(HW),HW=$(HW)) $(if $(IEC),IEC=$(IEC)) \
	    $(if $(ROM),ROM=$(ROM)) $(if $(SEEDS),SEEDS="$(SEEDS)") \
	    BIT_VERSION=$${BIT_VERSION:-$$(date +%y%m%d%H%M).0} bash run.sh; \
	else \
	    echo "Building the $(ARCH) desktop simulation..."; \
	    $(MAKE) -C $(call retrodir,$(ARCH))/sim-desktop all; \
	fi

run:
	$(need_arch)
	@if [ "$(TARGET)" = "fpga" ]; then \
	    $(MAKE) build ARCH=$(ARCH) TARGET=fpga; \
	else \
	    $(MAKE) -C $(call retrodir,$(ARCH))/sim-desktop run; \
	fi

# ── Prebuilt bitstreams ────────────────────────────────────────────────────
# `make bitstreams` regenerates the .bit files COMMITTED under bitstreams/ —
# what a fresh clone can flash without installing a toolchain.  They are legal
# to ship because the ROM arrays are EMPTY: the board loads the user's own
# ROMs after configuration.  NEVER add a ROM-baked bit here.
#
# Synthesis is SEQUENTIAL on purpose: the three run.sh scripts all rewrite the
# shared retro-arch/roms symlink, so a parallel build would feed one machine
# another's ROMs.
bitstreams:
	@for a in $(ARCHS); do \
	    echo "── $$a (ROM-free)"; \
	    ROMLESS=1 $(MAKE) build ARCH=$$a TARGET=fpga HW=v2 || exit 1; \
	    cp retro-arch/$$a/out.bit bitstreams/$$a-romless.bit || exit 1; \
	    printf '   -> bitstreams/%s-romless.bit  ' "$$a"; \
	    python3 util/bittag.py bitstreams/$$a-romless.bit | tail -1; \
	done
	@echo "Done. These are committed artifacts — see bitstreams/README.md."

# ── Desktop companion app (PySide6) ────────────────────────────────────────
# `make desktop` provisions desktop/.venv on first run (pinned requirements),
# then launches the GUI.  The venv and the downloaded game library are
# gitignored and are NOT touched by `make clean`.
DESKTOP_DIR  := desktop
DESKTOP_VENV := $(DESKTOP_DIR)/.venv
DESKTOP_PY   := $(DESKTOP_VENV)/bin/python

desktop-venv: $(DESKTOP_VENV)/.stamp
$(DESKTOP_VENV)/.stamp: $(DESKTOP_DIR)/requirements.txt
	@echo "Provisioning $(DESKTOP_VENV)..."
	@python3 -m venv $(DESKTOP_VENV)
	@$(DESKTOP_PY) -m pip install --upgrade pip >/dev/null
	@$(DESKTOP_PY) -m pip install -r $(DESKTOP_DIR)/requirements.txt
	@touch $@

desktop: desktop-venv
	@echo "Launching the fpgago desktop app..."
	@cd $(DESKTOP_DIR) && .venv/bin/python -m app.main

# `make start` — the one command for new users.
start:
	@command -v python3 >/dev/null 2>&1 || { \
	    printf "python3 not found — install it first:\n"; \
	    printf "  macOS:  xcode-select --install   (or: brew install python3)\n"; \
	    printf "  Debian: sudo apt install python3 python3-venv\n"; \
	    printf "  Fedora: sudo dnf install python3\n"; \
	    exit 1; }
	@FPGAGO_INSTALL_TAB=1 $(MAKE) desktop

# ── Clean ──────────────────────────────────────────────────────────────────
# NEVER sweep bitstreams/ from here: those .bit files are COMMITTED artifacts
# (the ROM-free builds a fresh clone flashes), not build output.  Same rule as
# desktop/.venv — `make bitstreams` is what rewrites them.
clean:
	@echo "Cleaning simulators..."
	@for d in retro-arch/*/sim-desktop; do \
	    [ -f "$$d/Makefile" ] && $(MAKE) -C "$$d" clean 2>/dev/null || true; \
	done
	@$(MAKE) -C retro-arch/common/drive1541 clean 2>/dev/null || true
	@$(MAKE) -C retro-arch/common/cpu/6502 clean 2>/dev/null || true
	@echo "Cleaning synthesis output..."
	@rm -f retro-arch/*/out.bit retro-arch/*/out.config retro-arch/*/out.json \
	       retro-arch/*/out.timing retro-arch/*/out.version retro-arch/*/out.pnr.log
	@# run.sh points this at the machine being synthesized; a stale one would
	@# feed the next build another machine's ROMs.
	@rm -f retro-arch/roms
	@echo "Cleaning stray Verilator output..."
	@find retro-arch -type d -name 'obj_dir*' -prune -exec rm -rf {} + 2>/dev/null || true
	@find retro-arch -type d -name '__pycache__' -prune -exec rm -rf {} + 2>/dev/null || true
	@echo "Done."
