# fpga_gameconsole/Makefile — Global build orchestrator
#
# Build & Run:
#   make all                                                — build all games, all platforms
#   make build GAME=<game> ARCH=<arch>                      — build ROM only
#   make build GAME=<game> TARGET=sdl2                      — build native SDL2 binary
#   make run   GAME=<game> ARCH=<arch> TARGET=<target>      — build + run
#   make clean                                              — clean build artifacts
#
# Targets (TARGET=):
#   sdl2      — native desktop build (gcc + SDL2)
#   verilator — desktop sim running actual Verilog (Verilator + SDL2)
#   fpga      — yosys/nextpnr synthesis to bitfile for real hardware
#   gtkwave   — iverilog simulation to VCD waveform
#
# Create & Manage:
#   make copyarch SRC=<arch> DST=<name>                     — copy an architecture
#   make delarch  ARCH=<name>                               — delete a user-created arch
#   make newgame  GAME=<name> ARCH=<arch>                   — scaffold a new game
#   make delgame  GAME=<name>                               — delete a user-created game
#
# Retro Computers (ARCH=pet, spectrum):
#   make download-rom ARCH=<arch>                           — download firmware ROMs
#   make download-cpu ARCH=<arch>                           — download CPU core (if needed)
#   make run ARCH=<arch>                                    — run retro computer simulation
#   make download-game ARCH=pet GAME=<name>                 — download a game
#   make run-game ARCH=pet GAME=<name>                      — run a game
#   make list-games ARCH=pet                                — list available games
#
# Setup:
#   make check-deps                                         — check installed tools
#
# Examples:
#   make run   GAME=char-snake ARCH=risc1 TARGET=verilator
#   make run   GAME=tic-tac-toe TARGET=sdl2
#   make download-rom ARCH=spectrum
#   make run ARCH=pet

# Load tool paths from .config.mk (generated by ./setup.sh)
-include .config.mk

ifeq ($(OS),Windows_NT)
  EXEEXT = .exe
else
  EXEEXT =
endif

# Prevent TARGET from leaking into sub-Makefiles (many use TARGET for binary name)
MAKEOVERRIDES := $(filter-out TARGET=%,$(MAKEOVERRIDES))

# ── Game/platform matrix ────────────────────────────────────────────────────
GAMES_RISC1 = char-snake
GAMES_RISC2 = gomoku tic-tac-toe char-gomoku labyrinth chess hello-pixels
GAMES_SDL2  = gomoku tic-tac-toe labyrinth char-gomoku chess hello-pixels

.PHONY: help all build run clean all-sdl2 all-risc1 all-risc2 gcasm check-deps copyarch delarch newgame delgame \
       download-rom download-cpu download-game run-game list-games

# ── Default target: show help ──────────────────────────────────────────────
help:
	@printf "\n"
	@printf "\033[1;32m  FPGAgo Build System\033[0m\n"
	@printf "\n"
	@printf "\033[32m  Build & Run:\033[0m\n"
	@printf "    make all                                       Build all games, all platforms\n"
	@printf "    make build GAME=<game> ARCH=<arch>             Build ROM only\n"
	@printf "    make build GAME=<game> TARGET=sdl2             Build native SDL2 binary\n"
	@printf "    make run   GAME=<game> ARCH=<arch> TARGET=<t>  Build + run\n"
	@printf "    make clean                                     Clean build artifacts\n"
	@printf "\n"
	@printf "\033[32m  Targets (TARGET=):\033[0m\n"
	@printf "    sdl2       Native desktop (gcc + SDL2)\n"
	@printf "    verilator  Desktop sim with real Verilog (Verilator + SDL2)\n"
	@printf "    fpga       Synthesize bitfile (yosys + nextpnr)\n"
	@printf "    gtkwave    Waveform simulation (iverilog)\n"
	@printf "\n"
	@printf "\033[32m  Create & Manage:\033[0m\n"
	@printf "    make copyarch SRC=<arch> DST=<name>            Copy an architecture\n"
	@printf "    make delarch  ARCH=<name>                      Delete a user-created arch\n"
	@printf "    make newgame  GAME=<name> ARCH=<arch>          Scaffold a new game\n"
	@printf "    make delgame  GAME=<name>                      Delete a user-created game\n"
	@printf "\n"
	@printf "\033[32m  Retro Computers (ARCH=pet, spectrum, c64):\033[0m\n"
	@printf "    make download-rom  ARCH=<arch>                 Download firmware ROMs\n"
	@printf "    make download-cpu  ARCH=<arch>                 Download CPU core (if needed)\n"
	@printf "    make run           ARCH=<arch>                 Run retro computer simulation\n"
	@printf "    make download-game ARCH=pet GAME=<name>        Download a game\n"
	@printf "    make run-game      ARCH=pet GAME=<name>        Run a game\n"
	@printf "    make list-games    ARCH=pet                    List available games\n"
	@printf "\n"
	@printf "\033[32m  Setup:\033[0m\n"
	@printf "    make check-deps                                Check installed tools\n"
	@printf "\n"
	@printf "\033[32m  Examples:\033[0m\n"
	@printf "    make run   GAME=char-snake ARCH=risc1 TARGET=verilator\n"
	@printf "    make run   GAME=tic-tac-toe TARGET=sdl2\n"
	@printf "    make download-rom ARCH=spectrum\n"
	@printf "    make run ARCH=pet\n"
	@printf "\n"

# ── Check dependencies ─────────────────────────────────────────────────────
check-deps:
	@bash setup.sh check

# ── Build gcasm (assembler) ────────────────────────────────────────────────
gcasm:
	$(MAKE) -C util/gcasm

# ── Build everything ────────────────────────────────────────────────────────
all: gcasm all-sdl2 all-risc1 all-risc2

all-sdl2:
	@for g in $(GAMES_SDL2); do \
	    echo "=== $$g (sdl2) ===" && \
	    $(MAKE) build GAME=$$g TARGET=sdl2; \
	done

all-risc1: gcasm
	@for g in $(GAMES_RISC1); do \
	    echo "=== $$g (risc1) ===" && \
	    $(MAKE) build GAME=$$g ARCH=risc1; \
	done

all-risc2: gcasm
	@for g in $(GAMES_RISC2); do \
	    echo "=== $$g (risc2) ===" && \
	    $(MAKE) build GAME=$$g ARCH=risc2; \
	done

# ── Retro computers (unified ARCH= interface) ─────────────────────────────
# Architectures with sim-desktop that run standalone (no GAME needed)
RETRO_ARCHS = pet plus4 c16 spectrum c64

download-rom:
	@test -n "$(ARCH)" || { echo "Usage: make download-rom ARCH=<arch>"; echo "Available: $(RETRO_ARCHS)"; exit 1; }
	@test -d arch/$(ARCH)/sim-desktop || { echo "Error: arch/$(ARCH) is not a retro computer"; exit 1; }
	@$(MAKE) -C arch/$(ARCH)/sim-desktop download-$(ARCH)-rom

download-cpu:
	@test -n "$(ARCH)" || { echo "Usage: make download-cpu ARCH=<arch>"; exit 1; }
	@test -d arch/$(ARCH)/sim-desktop || { echo "Error: arch/$(ARCH) is not a retro computer"; exit 1; }
	@$(MAKE) -C arch/$(ARCH)/sim-desktop download-cpu

download-game:
	@test -n "$(ARCH)" -a -n "$(GAME)" || { echo "Usage: make download-game ARCH=<arch> GAME=<name>"; exit 1; }
	@$(MAKE) -C arch/$(ARCH)/sim-desktop download-$(ARCH)-game GAME=$(GAME)

run-game:
	@test -n "$(ARCH)" -a -n "$(GAME)" || { echo "Usage: make run-game ARCH=<arch> GAME=<name>"; exit 1; }
	@$(MAKE) -C arch/$(ARCH)/sim-desktop run-$(ARCH)-game GAME=$(GAME)

list-games:
	@test -n "$(ARCH)" || { echo "Usage: make list-games ARCH=<arch>"; exit 1; }
	@$(MAKE) -C arch/$(ARCH)/sim-desktop list-$(ARCH)-games

# ── Build a single game ────────────────────────────────────────────────────
build: gcasm
	@test -n "$(GAME)" || { echo "Usage: make build GAME=<game> [ARCH=<arch>] [TARGET=sdl2]"; exit 1; }
	@if [ "$(TARGET)" = "sdl2" ]; then \
	    echo "Building $(GAME) for SDL2..." && \
	    if [ -d "games/$(GAME)/src/platform/sdl2" ] && [ -f "games/$(GAME)/src/platform/sdl2/Makefile" ]; then \
	        $(MAKE) -C games/$(GAME)/src/platform/sdl2; \
	    else \
	        $(MAKE) -C games/$(GAME); \
	    fi; \
	elif [ "$(ARCH)" = "risc1" ]; then \
	    echo "Building $(GAME) for RISC1..." && \
	    $(MAKE) -C games/$(GAME); \
	elif [ -n "$(ARCH)" ]; then \
	    echo "Building $(GAME) for $(ARCH)..." && \
	    $(MAKE) -C games/$(GAME)/src/platform/$(ARCH); \
	else \
	    echo "Error: specify ARCH=<arch> or TARGET=sdl2"; exit 1; \
	fi

# ── Build + run ─────────────────────────────────────────────────────────────
# For retro computers (no GAME): make run ARCH=pet / make run ARCH=spectrum
run:
	@if [ -z "$(GAME)" ] && [ -n "$(ARCH)" ] && [ -d "arch/$(ARCH)/sim-desktop" ]; then \
	    $(MAKE) -C arch/$(ARCH)/sim-desktop run; \
	    exit 0; \
	fi; \
	$(MAKE) build GAME=$(GAME) ARCH=$(ARCH) TARGET=$(TARGET); \
	if [ "$(TARGET)" = "sdl2" ]; then \
	    if [ -d "games/$(GAME)/src/platform/sdl2" ] && [ -f "games/$(GAME)/src/platform/sdl2/Makefile" ]; then \
	        cd games/$(GAME)/src/platform/sdl2 && ./$(GAME)$(EXEEXT); \
	    else \
	        $(MAKE) -C games/$(GAME) run; \
	    fi; \
	elif [ "$(TARGET)" = "verilator" ] || [ "$(TARGET)" = "fpga" ] || [ "$(TARGET)" = "gtkwave" ]; then \
	    if [ "$(ARCH)" = "risc1" ]; then \
	        $(MAKE) -C games/$(GAME) copy && \
	        if [ "$(TARGET)" = "verilator" ]; then $(MAKE) -C arch/risc1/sim-desktop run SIM_GAME=$(GAME) SIM_ARCH=$(ARCH); \
	        elif [ "$(TARGET)" = "fpga" ]; then cd arch/risc1 && bash run.sh; \
	        else cd arch/risc1 && bash simulate.sh; fi; \
	    else \
	        $(MAKE) -C games/$(GAME)/src/platform/$(ARCH) run-$(TARGET) SIM_GAME=$(GAME) SIM_ARCH=$(ARCH); \
	    fi; \
	else \
	    echo "Error: specify TARGET=sdl2|verilator|fpga|gtkwave"; exit 1; \
	fi

# ── Clean everything ───────────────────────────────────────────────────────
clean:
	@echo "Cleaning games..."
	@for d in $$(find games -name Makefile -path '*/platform/*/Makefile' -exec dirname {} \;); do \
	    $(MAKE) -C "$$d" clean 2>/dev/null || true; \
	done
	@$(MAKE) -C games/char-snake clean 2>/dev/null || true
	@echo "Cleaning simulators..."
	@for d in arch/*/sim-desktop; do \
	    [ -f "$$d/Makefile" ] && $(MAKE) -C "$$d" clean 2>/dev/null || true; \
	done
	@echo "Cleaning ROM artifacts..."
	@rm -f arch/*/rom.bin arch/*/rom.hex arch/*/romL.vh arch/*/romH.vh arch/*/rom.vh
	@rm -f rom.bin rom.hex romL.vh romH.vh romL2.vh romH2.vh
	@echo "Cleaning gcasm..."
	@$(MAKE) -C util/gcasm clean 2>/dev/null || true

# ── Copy architecture ──────────────────────────────────────────────────────
# Usage: make copyarch SRC=risc1 DST=risc1-myversion
copyarch:
	@test -n "$(SRC)" -a -n "$(DST)" || { echo "Usage: make copyarch SRC=<arch> DST=<name>"; exit 1; }
	@test -d arch/$(SRC) || { echo "Error: arch/$(SRC) not found"; exit 1; }
	@test ! -d arch/$(DST) || { echo "Error: arch/$(DST) already exists"; exit 1; }
	@case "$(DST)" in risc1|risc2) echo "Error: cannot overwrite built-in arch '$(DST)'"; exit 1;; esac
	@echo "Copying arch/$(SRC) -> arch/$(DST)..."
	@cp -R arch/$(SRC) arch/$(DST)
	@# Determine base ISA: read from .user-arch if copying a user arch, else SRC is the base
	@if [ -f arch/$(SRC)/.user-arch ]; then \
	    base_isa=$$(cat arch/$(SRC)/.user-arch); \
	else \
	    base_isa=$(SRC); \
	fi; \
	echo "$$base_isa" > arch/$(DST)/.user-arch; \
	echo "  Base ISA: $$base_isa"; \
	bash util/gcasm-copyarch.sh $(DST) $$base_isa $(SRC); \
	$(MAKE) -C util/gcasm clean && $(MAKE) -C util/gcasm
	@rm -f arch/$(DST)/rom.bin arch/$(DST)/rom.hex arch/$(DST)/romL.vh \
	       arch/$(DST)/romH.vh arch/$(DST)/rom.vh arch/$(DST)/romL2.vh arch/$(DST)/romH2.vh
	@rm -rf arch/$(DST)/sim-desktop/obj_dir
	@# Fix ARCH_DIR and ISA_NAME in copied build.mk
	@if [ -f arch/$(DST)/build.mk ]; then \
	    sed -e 's|arch/$(SRC)|arch/$(DST)|g' \
	        -e 's|ISA_NAME.*= $(SRC)|ISA_NAME     ?= $(DST)|' \
	        arch/$(DST)/build.mk > arch/$(DST)/build.mk.tmp && \
	    mv arch/$(DST)/build.mk.tmp arch/$(DST)/build.mk; \
	fi
	@# Create game platform directories
	@if [ -f arch/$(SRC)/.user-arch ]; then \
	    base_isa=$$(cat arch/$(SRC)/.user-arch); \
	else \
	    base_isa=$(SRC); \
	fi; \
	if [ "$$base_isa" = "risc1" ]; then \
	    for g in $(GAMES_RISC1); do \
	        echo "  Creating games/$$g/src/platform/$(DST)/"; \
	        mkdir -p games/$$g/src/platform/$(DST); \
	        bash util/gen-risc1-platform.sh $(DST) games/$$g/src/platform/$(DST)/Makefile; \
	    done; \
	elif [ "$$base_isa" = "risc2" ]; then \
	    for g in $(GAMES_RISC2); do \
	        echo "  Creating games/$$g/src/platform/$(DST)/"; \
	        if [ -d games/$$g/src/platform/$(SRC) ]; then \
	            cp -R games/$$g/src/platform/$(SRC) games/$$g/src/platform/$(DST); \
	            sed "s|arch/$(SRC)|arch/$(DST)|g" \
	                games/$$g/src/platform/$(SRC)/Makefile \
	                > games/$$g/src/platform/$(DST)/Makefile; \
	        else \
	            cp -R games/$$g/src/platform/$$base_isa games/$$g/src/platform/$(DST); \
	            sed "s|arch/$$base_isa/build.mk|arch/$(DST)/build.mk|" \
	                games/$$g/src/platform/$$base_isa/Makefile \
	                > games/$$g/src/platform/$(DST)/Makefile; \
	        fi; \
	    done; \
	else \
	    for src_dir in $$(find games -path "*/platform/$(SRC)" -type d 2>/dev/null); do \
	        dst_dir=$$(echo "$$src_dir" | sed "s|/$(SRC)$$|/$(DST)|"); \
	        echo "  Creating $$dst_dir/"; \
	        cp -R "$$src_dir" "$$dst_dir"; \
	        sed 's|arch/$(SRC)|arch/$(DST)|g' "$$src_dir/Makefile" > "$$dst_dir/Makefile"; \
	    done; \
	fi
	@echo ""
	@echo "Created arch/$(DST) (copy of $(SRC))"
	@echo "Usage: make run GAME=<game> ARCH=$(DST) TARGET=verilator"

# ── Delete user architecture ──────────────────────────────────────────────
# Usage: make delarch ARCH=risc1-myversion
delarch:
	@test -n "$(ARCH)" || { echo "Usage: make delarch ARCH=<name>"; exit 1; }
	@test -f arch/$(ARCH)/.user-arch || { echo "Error: arch/$(ARCH) is not a user-created arch (or does not exist)"; exit 1; }
	@# Block if any game depends on this arch
	@deps=""; \
	for gdir in $$(find games -path "*/platform/$(ARCH)" -type d 2>/dev/null \
	    | sed 's|games/\([^/]*\)/.*|\1|' | sort -u); do \
	    if [ -f "games/$$gdir/.user-game" ]; then \
	        deps="$$deps $$gdir"; \
	    fi; \
	done; \
	for mf in games/*/Makefile; do \
	    if grep -q "arch/$(ARCH)" "$$mf" 2>/dev/null; then \
	        g=$$(echo "$$mf" | sed 's|games/\([^/]*\)/.*|\1|'); \
	        echo "$$deps" | grep -qw "$$g" || deps="$$deps $$g"; \
	    fi; \
	done; \
	if [ -n "$$deps" ]; then \
	    echo "Error: arch/$(ARCH) is still used by game(s):$$deps"; \
	    echo "Delete them first with: make delgame GAME=<name>"; \
	    exit 1; \
	fi
	@echo "Deleting arch/$(ARCH) and its platform dirs from other games..."
	@find games -path "*/platform/$(ARCH)" -type d -exec rm -rf {} + 2>/dev/null || true
	@rm -rf arch/$(ARCH)
	@# Remove gcasm mnemonic array + cpu_t entry and rebuild
	@arch_id=$$(echo "$(ARCH)" | tr '-' '_'); \
	sed "/^mnemonic_t $${arch_id}_mnemonics/,/^};/d" \
	    util/gcasm/user_mnemonics.inc > util/gcasm/user_mnemonics.inc.tmp && \
	    mv util/gcasm/user_mnemonics.inc.tmp util/gcasm/user_mnemonics.inc; \
	sed "/\"$(ARCH)\"/,/},/d" \
	    util/gcasm/user_archs.inc > util/gcasm/user_archs.inc.tmp && \
	    mv util/gcasm/user_archs.inc.tmp util/gcasm/user_archs.inc
	@$(MAKE) -C util/gcasm
	@echo "Done."

# ── Create new game ───────────────────────────────────────────────────────
# Usage: make newgame GAME=mygame ARCH=risc1
#        make newgame GAME=mygame ARCH=risc2
#        make newgame GAME=mygame ARCH=risc1-myversion
newgame:
	@test -n "$(GAME)" -a -n "$(ARCH)" || { echo "Usage: make newgame GAME=<name> ARCH=<arch>"; exit 1; }
	@test -d arch/$(ARCH) || { echo "Error: arch/$(ARCH) not found"; exit 1; }
	@test ! -d games/$(GAME) || { echo "Error: games/$(GAME) already exists"; exit 1; }
	@if [ -f arch/$(ARCH)/.user-arch ]; then \
	    base_isa=$$(cat arch/$(ARCH)/.user-arch); \
	else \
	    base_isa=$(ARCH); \
	fi; \
	echo "Creating game '$(GAME)' for arch '$(ARCH)' (base ISA: $$base_isa)..."; \
	bash util/newgame.sh $(GAME) $(ARCH) $$base_isa "$(CURDIR)"; \
	if [ "$$base_isa" = "risc1" ]; then \
	    echo "  Registering in GAMES_RISC1..."; \
	    sed 's/^GAMES_RISC1 = \(.*\)/GAMES_RISC1 = \1 $(GAME)/' Makefile > Makefile.tmp && \
	        mv Makefile.tmp Makefile; \
	    if [ "$(ARCH)" != "risc1" ]; then \
	        echo "  Creating platform/$(ARCH)/ for user arch..."; \
	        mkdir -p games/$(GAME)/src/platform/$(ARCH); \
	        bash util/gen-risc1-platform.sh $(ARCH) games/$(GAME)/src/platform/$(ARCH)/Makefile; \
	    fi; \
	elif [ "$$base_isa" = "risc2" ]; then \
	    echo "  Registering in GAMES_RISC2 and GAMES_SDL2..."; \
	    sed -e 's/^GAMES_RISC2 = \(.*\)/GAMES_RISC2 = \1 $(GAME)/' \
	        -e 's/^GAMES_SDL2  = \(.*\)/GAMES_SDL2  = \1 $(GAME)/' \
	        Makefile > Makefile.tmp && mv Makefile.tmp Makefile; \
	    if [ "$(ARCH)" != "$$base_isa" ]; then \
	        echo "  Creating platform/$(ARCH)/ for user arch..."; \
	        cp -R games/$(GAME)/src/platform/$$base_isa games/$(GAME)/src/platform/$(ARCH); \
	        sed "s|arch/$$base_isa/build.mk|arch/$(ARCH)/build.mk|" \
	            games/$(GAME)/src/platform/$$base_isa/Makefile \
	            > games/$(GAME)/src/platform/$(ARCH)/Makefile; \
	    fi; \
	fi
	@echo ""
	@echo "Game '$(GAME)' created! Try:"
	@if [ -f arch/$(ARCH)/.user-arch ]; then \
	    base_isa=$$(cat arch/$(ARCH)/.user-arch); \
	else \
	    base_isa=$(ARCH); \
	fi; \
	if [ "$$base_isa" = "risc1" ]; then \
	    echo "  make run GAME=$(GAME) ARCH=$(ARCH) TARGET=verilator"; \
	else \
	    echo "  make run GAME=$(GAME) TARGET=sdl2"; \
	    echo "  make run GAME=$(GAME) ARCH=$(ARCH) TARGET=verilator"; \
	fi

# ── Delete user game ─────────────────────────────────────────────────────
# Usage: make delgame GAME=mygame
delgame:
	@test -n "$(GAME)" || { echo "Usage: make delgame GAME=<name>"; exit 1; }
	@test -f games/$(GAME)/.user-game || { echo "Error: games/$(GAME) is not a user-created game (or does not exist)"; exit 1; }
	@echo "Deleting games/$(GAME)..."
	@rm -rf games/$(GAME)
	@# Unregister from game lists
	@sed -e 's/ $(GAME)$$//' \
	     -e 's/ $(GAME) / /g' \
	     Makefile > Makefile.tmp && mv Makefile.tmp Makefile
	@echo "Done."
