#!/usr/bin/env bash
# setup.sh — Install FPGAgo project dependencies
#
# Usage:
#   ./setup.sh          Install all dependencies (system packages + oss-cad-suite)
#   ./setup.sh check    Check which tools are already installed

set -euo pipefail

CMD="${1:-install}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OSS_CAD_DIR="$SCRIPT_DIR/oss-cad-suite"

# ── Colors (disabled when piped) ────────────────────────────────────────────
if [ -t 1 ]; then
    GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[0;33m'
    BOLD='\033[1m'; RESET='\033[0m'
else
    GREEN=''; RED=''; YELLOW=''; BOLD=''; RESET=''
fi

info()  { printf "${BOLD}==> %s${RESET}\n" "$*"; }
ok()    { printf "${GREEN} ✓  %s${RESET}\n" "$*"; }
warn()  { printf "${YELLOW} !  %s${RESET}\n" "$*"; }
fail()  { printf "${RED} ✗  %s${RESET}\n" "$*"; }

# ── OS detection ────────────────────────────────────────────────────────────
detect_os() {
    case "$(uname -s)" in
        Darwin)  echo "macos" ;;
        Linux)
            if   [ -f /etc/debian_version ];  then echo "debian"
            elif [ -f /etc/fedora-release ];   then echo "fedora"
            elif [ -f /etc/arch-release ];     then echo "arch"
            else echo "linux-unknown"; fi ;;
        MINGW*|MSYS*|CYGWIN*) echo "windows" ;;
        *) echo "unknown" ;;
    esac
}

OS="$(detect_os)"

# ── Write .config.mk ───────────────────────────────────────────────────────
write_config_mk() {
    local lines=()
    lines+=("# Generated by setup.sh — do not edit, do not commit")
    if [ -d "$OSS_CAD_DIR/bin" ]; then
        lines+=("export PATH := $OSS_CAD_DIR/bin:\$(PATH)")
    fi
    printf '%s\n' "${lines[@]}" > "$SCRIPT_DIR/.config.mk"
    ok "Config written to .config.mk"
}

# ── Download helper (curl with wget fallback) ──────────────────────────────
fetch() {
    # fetch <url> [-o <file>]
    if has curl; then
        curl -fSL "$@"
    elif has wget; then
        # translate curl flags to wget
        local url="" outfile=""
        while [ $# -gt 0 ]; do
            case "$1" in
                -o) outfile="$2"; shift 2 ;;
                -fSL|-fsSL|-fsS) shift ;;
                *) url="$1"; shift ;;
            esac
        done
        if [ -n "$outfile" ]; then
            wget -q --show-progress -O "$outfile" "$url"
        else
            wget -qO- "$url"
        fi
    else
        fail "Neither curl nor wget found. Install one and re-run."
        exit 1
    fi
}

# ── Tool check ──────────────────────────────────────────────────────────────
has() { command -v "$1" >/dev/null 2>&1; }

check_tool() {
    local cmd="$1" note="${2:-}"
    if has "$cmd"; then
        ok "$cmd  $(command -v "$cmd")"
    else
        fail "$cmd${note:+  — $note}"
    fi
}

do_check() {
    # Add OSS CAD Suite to PATH for tool detection
    if [ -d "$OSS_CAD_DIR/bin" ]; then
        export PATH="$OSS_CAD_DIR/bin:$PATH"
    fi

    info "Checking installed tools..."
    echo ""

    printf "${BOLD}%-20s %s${RESET}\n" "TOOL" "STATUS"
    echo "────────────────────────────────────────────"

    check_tool gcc
    check_tool make
    check_tool python3
    check_tool sdl2-config    "SDL2 development library"
    check_tool verilator
    check_tool iverilog
    check_tool gtkwave
    check_tool yosys
    check_tool nextpnr-ecp5
    check_tool ecppack

    echo ""
    info "OSS CAD Suite"
    if [ -x "$OSS_CAD_DIR/bin/nextpnr-ecp5" ]; then
        ok "Installed at $OSS_CAD_DIR"
    else
        fail "Not found (run ./setup.sh to install)"
    fi
}

# ── OSS CAD Suite (provides yosys, nextpnr-ecp5, ecppack, iverilog, gtkwave) ─

install_oss_cad_suite() {
    if [ -x "$OSS_CAD_DIR/bin/nextpnr-ecp5" ]; then
        ok "OSS CAD Suite already installed at $OSS_CAD_DIR"
        return
    fi

    info "Installing OSS CAD Suite (yosys, nextpnr-ecp5, ecppack, iverilog, gtkwave)..."
    local os_tag arch_tag url tarball
    case "$(uname -s)" in
        Darwin) os_tag="darwin" ;;
        Linux)  os_tag="linux" ;;
        *)      fail "OSS CAD Suite: unsupported OS"; return 1 ;;
    esac
    case "$(uname -m)" in
        x86_64)       arch_tag="x64" ;;
        arm64|aarch64) arch_tag="arm64" ;;
        *)            fail "OSS CAD Suite: unsupported arch $(uname -m)"; return 1 ;;
    esac

    # Fetch the latest release download URL from GitHub API
    url=$(fetch "https://api.github.com/repos/YosysHQ/oss-cad-suite-build/releases/latest" \
        | grep -o "\"browser_download_url\": *\"[^\"]*${os_tag}-${arch_tag}[^\"]*\"" \
        | head -1 | sed 's/.*"\(http[^"]*\)"/\1/')

    if [ -z "$url" ]; then
        fail "Could not find OSS CAD Suite release for ${os_tag}-${arch_tag}"
        warn "Download manually from: https://github.com/YosysHQ/oss-cad-suite-build/releases"
        return 1
    fi

    tarball="$(mktemp)"
    info "Downloading $url ..."
    fetch "$url" -o "$tarball"

    info "Extracting to $OSS_CAD_DIR ..."
    mkdir -p "$SCRIPT_DIR"
    tar -xzf "$tarball" -C "$SCRIPT_DIR"
    rm -f "$tarball"

    # The tarball extracts to oss-cad-suite/
    if [ ! -d "$OSS_CAD_DIR" ]; then
        # Handle case where tarball root dir has a different name
        local extracted
        extracted=$(ls -d "$SCRIPT_DIR"/oss-cad-suite* 2>/dev/null | head -1)
        if [ -n "$extracted" ] && [ "$extracted" != "$OSS_CAD_DIR" ]; then
            mv "$extracted" "$OSS_CAD_DIR"
        fi
    fi

    ok "OSS CAD Suite installed to $OSS_CAD_DIR"
}

# ── Install all system dependencies ────────────────────────────────────────

do_install() {
    info "Installing system packages..."
    case "$OS" in
        macos)
            brew install gcc make python3 sdl2 verilator
            ;;
        debian)
            sudo apt-get update
            sudo apt-get install -y \
                build-essential python3 python3-venv libsdl2-dev \
                verilator curl git
            ;;
        fedora)
            sudo dnf install -y \
                gcc gcc-c++ make python3 SDL2-devel \
                verilator curl git
            ;;
        arch)
            sudo pacman -S --needed \
                gcc make python sdl2 verilator curl git
            ;;
        windows)
            warn "Windows detected. Recommended: use WSL2 with Ubuntu, then re-run this script."
            warn "Alternatively, in MSYS2:"
            echo "  pacman -S mingw-w64-x86_64-gcc make python mingw-w64-x86_64-SDL2"
            ;;
        *)
            fail "Unsupported OS. Install manually: gcc, make, python3, SDL2, verilator"
            exit 1
            ;;
    esac

    echo ""
    install_oss_cad_suite

    echo ""
    write_config_mk

    echo ""
    info "Done! Verify with: ./setup.sh check"
    echo ""
    echo "Quick start:"
    echo "  make download-rom ARCH=c64     # your own ROM dumps, after consent"
    echo "  make run          ARCH=c64     # the desktop simulation"
    echo "  make build        ARCH=c64 TARGET=fpga   # synthesize a bitstream"
    echo ""
}

# ── Main ────────────────────────────────────────────────────────────────────

echo ""
echo "  FPGAgo Setup"
echo "  OS detected: $OS"
echo ""

case "$CMD" in
    install) do_install ;;
    check)   do_check ;;
    *)
        echo "Usage: $0 [install|check]"
        echo ""
        echo "  install   Install all dependencies (default)"
        echo "  check     Show which tools are installed"
        exit 1
        ;;
esac
