# arch/risc2/build.mk — Shared RISC2 C→ROM build pipeline
#
# New (flat) layout — include from games/<game>/Makefile after setting:
#   HAL_KIND     — "pixel" or "char" (auto-adds arch/risc2/hal_<kind>.c)
#   GAME_SRCS    — game C sources only (e.g., game.c render.c main.c)
#   EXTRA_CFLAGS — additional clang flags (optional)
#
# Legacy (platforms/) layout — still supported.  Per-game platforms/risc2/
# Makefile sets GAME_SRCS directly (including hal_risc2.c) and may override
# INCLUDE_DIRS / VPATH_DIRS.  HAL_KIND is left unset in that mode.
#
# Provides targets:
#   all          — build rom.bin
#   install      — copy ROM files to arch/risc2/
#   run-verilator — install + run Verilator SDL2 simulator
#   run-fpga     — install + synthesize + program FPGA
#   run-gtkwave  — install + iverilog waveform sim
#   clean

REPO_ROOT    ?= ../../../../../
ARCH_DIR     ?= $(REPO_ROOT)arch/risc2
INSTALL_DIR  ?= $(ARCH_DIR)
GCASM        ?= $(REPO_ROOT)util/gcasm/gcasm
ISA_NAME     ?= risc2

# Load CLANG path from .config.mk (generated by ./setup.sh llvm)
-include $(REPO_ROOT).config.mk
CLANG        ?= $(REPO_ROOT)llvm-risc2-build/bin/clang
INCLUDE_DIRS ?= ../../hal ../../engine $(ARCH_DIR) $(REPO_ROOT)/peripheral
VPATH_DIRS   ?= . ../../engine

# Flat-layout auto-include: when the per-game Makefile sets HAL_KIND, pull in
# the matching arch HAL file and make sure the arch dir is on VPATH+include
# paths.  Legacy platforms/risc2/Makefile leaves HAL_KIND empty.
ifneq ($(HAL_KIND),)
  GAME_SRCS    += hal_$(HAL_KIND).c
  VPATH_DIRS   += $(ARCH_DIR)
  INCLUDE_DIRS += . $(ARCH_DIR) $(REPO_ROOT)/peripheral
  # Games that have arch-conditional code (chess transposition table,
  # char-gomoku narrow text grid) key on RISC2_PLATFORM.
  EXTRA_CFLAGS += -DRISC2_PLATFORM
  BUILD_DIR     = build-risc2
endif

# Legacy platforms/ Makefile builds in cwd; flat layout uses a per-arch subdir.
BUILD_DIR ?= .

vpath %.c $(VPATH_DIRS)

BASE_CFLAGS = --target=risc2 -O1 -S -x c -fno-jump-tables -ffreestanding \
              $(addprefix -I,$(INCLUDE_DIRS))
ALL_CFLAGS  = $(BASE_CFLAGS) $(EXTRA_CFLAGS)

# Work around LLVM RISC2 frame-index lowering bug:
#   mov r7, r14 / add r7, #off / add rX, #0  →  mov rX, r14 / add rX, #off
FIX_FRAME = perl -0pe \
    's/\tmov r7, r14\n\tadd r7, \#([0-9a-f]+)\n\tadd (r\d+), \#0/\tmov $$2, r14\n\tadd $$2, \#$$1/g'

# Derive .asm filenames from C sources (strip path, swap extension), emit
# them into $(BUILD_DIR) so flat-layout builds don't clutter the game dir.
GAME_ASM = $(addprefix $(BUILD_DIR)/,$(notdir $(GAME_SRCS:.c=.asm)))
ALL_ASM  = $(ARCH_DIR)/startup.s $(ARCH_DIR)/runtime.s $(GAME_ASM)

# ── Check for RISC2 Clang ──────────────────────────────────────────────────
ifeq (,$(wildcard $(CLANG))$(wildcard $(CLANG).exe))
  $(info )
  $(info ERROR: RISC2 Clang not found at $(CLANG))
  $(info )
  $(info   RISC2 C games require a custom LLVM/Clang build.)
  $(info   Run './setup.sh llvm' (Linux/macOS) or 'setup.bat llvm' (Windows) to build it.)
  $(info )
  $(error RISC2 Clang not found)
endif

# ── Build targets ───────────────────────────────────────────────────────────
.PHONY: all clean install run-verilator run-fpga run-gtkwave

all: $(BUILD_DIR)/rom.bin

$(BUILD_DIR):
	@mkdir -p $@

# gcasm writes rom.bin / romL*.vh / romH*.vh / rom.hex into cwd, so for the
# flat (BUILD_DIR=build-risc2) case we cd into the build dir and run gcasm
# with absolute paths to the inputs and tool.  Legacy (BUILD_DIR=.) runs
# gcasm in place as before.
GCASM_ABS = $(abspath $(GCASM))
ASM_ABS   = $(foreach f,$(ALL_ASM),$(abspath $(f)))

$(BUILD_DIR)/rom.bin: $(ALL_ASM) | $(BUILD_DIR)
ifeq ($(BUILD_DIR),.)
	$(GCASM) -c$(ISA_NAME) $(ALL_ASM)
else
	cd $(BUILD_DIR) && $(GCASM_ABS) -c$(ISA_NAME) $(ASM_ABS)
endif

# Compile C → RISC2 assembly into $(BUILD_DIR)/.
# Label prefix is the uppercased filename stem (GAME, RENDER, MAIN, etc.)
# to avoid gcasm label collisions across files sharing one namespace.
#
# Header dependencies are captured via clang -MMD (writes %.d alongside the
# asm) and picked up with -include below.  Without this any TEX_W / TEX_SHIFT
# bump in texture.h would silently leave the .asm with stale shift constants.
$(BUILD_DIR)/%.asm: %.c | $(BUILD_DIR)
	$(CLANG) $(ALL_CFLAGS) -MMD -MF $(BUILD_DIR)/$*.d -MT $@ $< -o $@.tmp
	sed "s/_LBB/_$$(echo $* | tr a-z A-Z)_LBB/g" $@.tmp | $(FIX_FRAME) > $@
	@rm -f $@.tmp

-include $(addprefix $(BUILD_DIR)/,$(GAME_SRCS:.c=.d))

ROM_FILES = $(addprefix $(BUILD_DIR)/,rom.bin rom.hex \
            romL.vh romH.vh \
            $(foreach n,2 3 4 5 6 7 8,romL$(n).vh romH$(n).vh))

install: $(BUILD_DIR)/rom.bin
	@for f in $(ROM_FILES); do \
	  test -f $$f && cp $$f $(INSTALL_DIR)/ || true; \
	done

# ── Architecture run targets ────────────────────────────────────────────────
run-verilator: install
	$(MAKE) -C $(ARCH_DIR)/sim-desktop run SIM_GAME=$(SIM_GAME) SIM_ARCH=$(SIM_ARCH)

run-fpga: install
	cd $(ARCH_DIR) && HW=$(HW) bash run.sh

run-gtkwave: install
	cd $(ARCH_DIR) && bash simulate.sh

clean:
ifeq ($(BUILD_DIR),.)
	rm -f $(GAME_ASM) *.asm.tmp rom.bin romL*.vh romH*.vh rom.hex
else
	rm -rf $(BUILD_DIR)
endif
