/*
 * sid_tables.v — SID combined-waveform tables + 6581 filter curve
 *
 * yosys-safe port of the MiSTer C64 sid_tables.sv (GPL, from
 * randyrossi-adjacent MiSTer-devel/C64_MiSTer rtl/sid, itself based on
 * reSID / reDIP-SID by Dag Lem).  Functional behavior is unchanged;
 * differences are purely syntactic:
 *
 *   - the '{...} array literals became $readmemh ROMs
 *     (roms/sid_*.hex, regenerated by sid/mk_sid_tables.py from the
 *     upstream .sv) — yosys cannot parse assignment patterns, and
 *     readmemh is the EBR init path already board-proven by the c64
 *     BASIC/KERNAL ROMs.  NOTE: readmemh must stay ALONE in its initial
 *     block (no for-loop clear) or yosys silently drops the init.
 *   - each ROM gets its own registered read + a combinational 6581/8580
 *     mux AFTER the register (upstream muxed inside the sync read; two
 *     memories in one sync assignment can defeat yosys memory_dff and
 *     fall back to fabric).  Same 1-clock latency either way.
 *   - the MULTI_FILTERS=1 four-curve variant and the ld_* runtime
 *     filter-table load port (MiSTer ARM-side feature) are dropped:
 *     this build hardwires the MULTI_FILTERS=0 path = curve 0
 *     ("mixed calc") of the upstream table.
 */

module sid_tables
(
	input             clock,
	input             mode,       // 0 = 6581, 1 = 8580

	// combined waveforms
	input      [11:0] acc_t,
	output reg  [7:0] _st_out,
	output      [7:0] p_t_out,
	output      [7:0] ps__out,
	output reg  [7:0] pst_out,

	// filter cutoff
	input      [10:0] Fc,
	input      [12:0] Fc_offset,
	output     [15:0] F0
);

/* ── S+T / P+S+T: computed combinationally (registered), as upstream ──── */

always @(posedge clock) begin
	_st_out <= mode ? {
		((acc_t & 'he7e) == 'he7e) | ((acc_t & 'he80) == 'he80) | ((acc_t & 'hf00) == 'hf00) | ((acc_t & 'he7d) == 'he7d),
		((acc_t & 'h7f8) == 'h7f8) | ((acc_t & 'hf00) == 'hf00),
		((acc_t & 'h7e0) == 'h7e0) | ((acc_t & 'hf0f) == 'hf0f) | ((acc_t & 'hf1b) == 'hf1b) | ((acc_t & 'hbfe) == 'hbfe) | ((acc_t & 'hf1e) == 'hf1e) | ((acc_t & 'hf40) == 'hf40) | ((acc_t & 'hf30) == 'hf30) | ((acc_t & 'hf29) == 'hf29) | ((acc_t & 'hf26) == 'hf26) | ((acc_t & 'hf80) == 'hf80),
		((acc_t & 'h7e0) == 'h7e0) | ((acc_t & 'h3f0) == 'h3f0) | ((acc_t & 'hdfe) == 'hdfe) | ((acc_t & 'h5ff) == 'h5ff) | ((acc_t & 'hf80) == 'hf80),
		((acc_t & 'h7e0) == 'h7e0) | ((acc_t & 'h3f0) == 'h3f0) | ((acc_t & 'hfc0) == 'hfc0) | ((acc_t & 'h1f8) == 'h1f8) | ((acc_t & 'heff) == 'heff),
		((acc_t & 'h0fc) == 'h0fc) | ((acc_t & 'h1f8) == 'h1f8) | ((acc_t & 'h3f0) == 'h3f0) | ((acc_t & 'hfe0) == 'hfe0),
		((acc_t & 'h07e) == 'h07e) | ((acc_t & 'hff0) == 'hff0) | ((acc_t & 'h7f7) == 'h7f7) | ((acc_t & 'h1f8) == 'h1f8) | ((acc_t & 'h0fc) == 'h0fc),
		((acc_t & 'hdbf) == 'hdbf) | ((acc_t & 'h0fc) == 'h0fc) | ((acc_t & 'h3fa) == 'h3fa) | ((acc_t & 'h7f8) == 'h7f8) | ((acc_t & 'h3bf) == 'h3bf) | ((acc_t & 'h07e) == 'h07e)
	} : {
		1'b0,
		((acc_t & 'h7fc) == 'h7fc),
		((acc_t & 'h7e0) == 'h7e0) | ((acc_t & 'h3fe) == 'h3fe),
		((acc_t & 'h7e0) == 'h7e0) | ((acc_t & 'h5ff) == 'h5ff) | ((acc_t & 'h3f0) == 'h3f0),
		((acc_t & 'h7e0) == 'h7e0) | ((acc_t & 'h1f8) == 'h1f8) | ((acc_t & 'h3f0) == 'h3f0),
		((acc_t & 'h0fc) == 'h0fc) | ((acc_t & 'h1f8) == 'h1f8) | ((acc_t & 'h3f0) == 'h3f0),
		((acc_t & 'h07e) == 'h07e) | ((acc_t & 'h1f8) == 'h1f8) | ((acc_t & 'h0fc) == 'h0fc),
		((acc_t & 'h13f) == 'h13f) | ((acc_t & 'h07e) == 'h07e) | ((acc_t & 'h7fa) == 'h7fa) | ((acc_t & 'h0bf) == 'h0bf) | ((acc_t & 'h0fc) == 'h0fc)
	};
end

always @(posedge clock) begin
	pst_out <= mode ? {
		((acc_t & 'he89) == 'he89) | ((acc_t & 'he3e) == 'he3e) | ((acc_t & 'hec0) == 'hec0) | ((acc_t & 'he8a) == 'he8a) | ((acc_t & 'hdf7) == 'hdf7) | ((acc_t & 'hdf8) == 'hdf8) | ((acc_t & 'he85) == 'he85) | ((acc_t & 'he6a) == 'he6a) | ((acc_t & 'he90) == 'he90) | ((acc_t & 'he83) == 'he83) | ((acc_t & 'he67) == 'he67) | ((acc_t & 'hea0) == 'hea0) | ((acc_t & 'hf00) == 'hf00) | ((acc_t & 'he5e) == 'he5e) | ((acc_t & 'he70) == 'he70) | ((acc_t & 'he6c) == 'he6c),
		((acc_t & 'heee) == 'heee) | ((acc_t & 'h7ef) == 'h7ef) | ((acc_t & 'h7f2) == 'h7f2) | ((acc_t & 'h7f4) == 'h7f4) | ((acc_t & 'hef0) == 'hef0) | ((acc_t & 'h7f8) == 'h7f8) | ((acc_t & 'hf00) == 'hf00) | ((acc_t & 'h7f1) == 'h7f1),
		((acc_t & 'hf78) == 'hf78) | ((acc_t & 'h7f0) == 'h7f0) | ((acc_t & 'h7ee) == 'h7ee) | ((acc_t & 'hf74) == 'hf74) | ((acc_t & 'hf6f) == 'hf6f) | ((acc_t & 'hf80) == 'hf80) | ((acc_t & 'hbff) == 'hbff),
		((acc_t & 'hdff) == 'hdff) | ((acc_t & 'hbfe) == 'hbfe) | ((acc_t & 'h7ef) == 'h7ef) | ((acc_t & 'h7f2) == 'h7f2) | ((acc_t & 'h3ff) == 'h3ff) | ((acc_t & 'h7f4) == 'h7f4) | ((acc_t & 'hfc0) == 'hfc0) | ((acc_t & 'hfb8) == 'hfb8) | ((acc_t & 'h7f8) == 'h7f8) | ((acc_t & 'hfb6) == 'hfb6),
		((acc_t & 'hbfe) == 'hbfe) | ((acc_t & 'hfdc) == 'hfdc) | ((acc_t & 'hdfe) == 'hdfe) | ((acc_t & 'h7f7) == 'h7f7) | ((acc_t & 'hfda) == 'hfda) | ((acc_t & 'hbfd) == 'hbfd) | ((acc_t & 'h7f8) == 'h7f8) | ((acc_t & 'h3ff) == 'h3ff) | ((acc_t & 'hfe0) == 'hfe0) | ((acc_t & 'heff) == 'heff),
		((acc_t & 'hfeb) == 'hfeb) | ((acc_t & 'h7fa) == 'h7fa) | ((acc_t & 'hbfe) == 'hbfe) | ((acc_t & 'hdfe) == 'hdfe) | ((acc_t & 'hff0) == 'hff0) | ((acc_t & 'h7fc) == 'h7fc) | ((acc_t & 'h3ff) == 'h3ff) | ((acc_t & 'hfec) == 'hfec) | ((acc_t & 'heff) == 'heff),
		((acc_t & 'hff6) == 'hff6) | ((acc_t & 'hdff) == 'hdff) | ((acc_t & 'hf7f) == 'hf7f) | ((acc_t & 'hbfe) == 'hbfe) | ((acc_t & 'h7fc) == 'h7fc) | ((acc_t & 'hff5) == 'hff5) | ((acc_t & 'h3ff) == 'h3ff) | ((acc_t & 'hff8) == 'hff8) | ((acc_t & 'heff) == 'heff),
		((acc_t & 'hdff) == 'hdff) | ((acc_t & 'hf7f) == 'hf7f) | ((acc_t & 'hffa) == 'hffa) | ((acc_t & 'h7fe) == 'h7fe) | ((acc_t & 'hff9) == 'hff9) | ((acc_t & 'hffc) == 'hffc) | ((acc_t & 'h3ff) == 'h3ff) | ((acc_t & 'heff) == 'heff)
	} : {
		1'b0,
		((acc_t & 'h7fc) == 'h7fc) | ((acc_t & 'h7fb) == 'h7fb),
		((acc_t & 'h7ef) == 'h7ef) | ((acc_t & 'h7f7) == 'h7f7) | ((acc_t & 'h7fc) == 'h7fc) | ((acc_t & 'h7fb) == 'h7fb) | ((acc_t & 'h3ff) == 'h3ff),
		((acc_t & 'h7fc) == 'h7fc) | ((acc_t & 'h3ff) == 'h3ff) | ((acc_t & 'h7f7) == 'h7f7) | ((acc_t & 'h7fb) == 'h7fb),
		((acc_t & 'h7fc) == 'h7fc) | ((acc_t & 'h3ff) == 'h3ff) | ((acc_t & 'h7fb) == 'h7fb),
		((acc_t & 'h7fd) == 'h7fd) | ((acc_t & 'h3ff) == 'h3ff) | ((acc_t & 'h7fe) == 'h7fe),
		((acc_t & 'h7fd) == 'h7fd) | ((acc_t & 'h3ff) == 'h3ff) | ((acc_t & 'h7fe) == 'h7fe),
		((acc_t & 'h3ff) == 'h3ff) | ((acc_t & 'h7fe) == 'h7fe)
	};
end

/* ── P+T / P+S: sampled wave ROMs ─────────────────────────────────────── */

reg [7:0] wave6581_p_t [0:2047];
reg [7:0] wave6581_ps_ [0:2047];
reg [7:0] wave8580_p_t [0:2047];
reg [7:0] wave8580_ps_ [0:4095];

initial $readmemh("../roms/sid_wave6581_pt.hex", wave6581_p_t);
initial $readmemh("../roms/sid_wave6581_ps.hex", wave6581_ps_);
initial $readmemh("../roms/sid_wave8580_pt.hex", wave8580_p_t);
initial $readmemh("../roms/sid_wave8580_ps.hex", wave8580_ps_);

reg [7:0] pt6581_q, pt8580_q, ps6581_q, ps8580_q;
always @(posedge clock) begin
	pt6581_q <= wave6581_p_t[acc_t[10:0]];
	pt8580_q <= wave8580_p_t[acc_t[10:0]];
	ps6581_q <= wave6581_ps_[acc_t[10:0]];
	ps8580_q <= wave8580_ps_[acc_t];
end

assign p_t_out = mode ? pt8580_q : pt6581_q;
assign ps__out = mode ? ps8580_q : ps6581_q;

/* ── 6581 filter cutoff curve (F0) ────────────────────────────────────── */

reg [15:0] f6581_curve [0:1023];
reg [14:0] f6581_adj   [0:1023];

initial $readmemh("../roms/sid_f6581_curve.hex", f6581_curve);
initial $readmemh("../roms/sid_f6581_adj.hex",   f6581_adj);

reg [15:0] f0;
always @(posedge clock) f0 <= f6581_curve[Fc[10:1]];

wire [10:0] fc_6581;
sid_dac #(.BITS(11)) fc_dac
(
	.vin  (Fc),
	.vout (fc_6581)
);

function [9:0] tanh_x_mirror(input signed [10:0] x);
	tanh_x_mirror = x[10] ? (~x + 1'b1) : x;
endfunction

function signed [10:0] tanh_x_clamp(input signed [12:0] x);
	tanh_x_clamp = (x < -13'sd1023) ? -11'sd1023 :
	               (x >  13'sd1023) ?  11'sd1023 :
	               x[10:0];
endfunction

function signed [15:0] tanh_y_mirror(input x_neg, input signed [15:0] y);
	tanh_y_mirror = x_neg ? (-y) : y;
endfunction

localparam signed [15:0] F6581_ADJ_Y0 = 16'sd10133;  // 9883 + 250

wire signed [10:0] fc_x = tanh_x_clamp({2'b00, fc_6581} - Fc_offset);

reg        fc_x_sign_q;
reg [14:0] f0_adj_q;
always @(posedge clock) begin
	fc_x_sign_q <= fc_x[10];
	f0_adj_q    <= f6581_adj[tanh_x_mirror(fc_x)];
end

assign F0 = mode          ? ({3'b000, Fc, 2'b00} + Fc) :
            (|Fc_offset)  ? (F6581_ADJ_Y0 +
                             tanh_y_mirror(fc_x_sign_q, {1'b0, f0_adj_q})) :
                            {1'b0, f0[15:1]};

endmodule
